/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package type_object_pattern;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //erstelt verschiedene monstertypen mit der monstertype class
        final MonsterTypeClass RAT = new MonsterTypeClass("Rat", 20, 20, "piep");
        final MonsterTypeClass KERBEROS = new MonsterTypeClass("Kerberos", 1000, 500, "grr");
        final MonsterTypeClass HELLCAT = new MonsterTypeClass("Hellcat", 500, 250, "fauch");

        //erstellt verschiedene monstertypen mit dem vererbungskonstruktor der monstertype class
        final MonsterTypeClass BOSS_RAT = new MonsterTypeClass(RAT, 100, 50);
        final MonsterTypeClass BOSS_KERBEROS = new MonsterTypeClass(KERBEROS, 2000, 1000);
        final MonsterTypeClass BOSS_HELLCAT = new MonsterTypeClass(HELLCAT, 750, 500);

        //erstellt verschiedene monster mit den monstertypen und der monFac methode.
        Monster rat = RAT.monFac();
        Monster kerberos = KERBEROS.monFac();
        Monster hellcat = HELLCAT.monFac();
        Monster bossRat = BOSS_RAT.monFac();
        Monster bossKerberos = BOSS_KERBEROS.monFac();
        Monster bossHellcat = BOSS_HELLCAT.monFac();

        //erstellt verschiede monster mithilfe des enums
        Monster ratEnum = new Monster(RAT);
        Monster kerberosEnum = new Monster(KERBEROS);
        Monster hellcatEnum = new Monster(HELLCAT);

        //lässt die normalen monster ein geräusch machen
        System.out.println("Monstergeraeusche");
        System.out.println("Ratte: " + rat.makeNoise());
        System.out.println("Kerberos: " + kerberos.makeNoise());
        System.out.println("Hellcat: " + hellcat.makeNoise());
        System.out.println("RatteEnum: " + ratEnum.makeNoise());
        System.out.println("KerberosEnum: " + kerberosEnum.makeNoise());
        System.out.println("HellcatEnum: " + hellcatEnum.makeNoise());
        
        //zeigt die vererbung bezüglich des type-objects
        System.out.println("\nObejectPattern-Vererbung");
        System.out.println(rat.toString());
        System.out.println(bossRat.toString());
        System.out.println(kerberos.toString());
        System.out.println(bossKerberos.toString());
        System.out.println(hellcat.toString());
        System.out.println(bossHellcat.toString());
    }
}
